### ISSUE TITLE
Meta-dados dos dados no resultado

### ISSUE THREAD

**Issue by everton3x** [iddrs/cont-test#3]
Colocar na saída dos resultados os seguintes meta-dados:

- [x] Data inicial e final dos dados
- [x] Data da geração dos dados
- [x] Data da realização dos testes

**Comment by everton3x** [comment]
4bd3903323166566604b9153faf0ee4813d284da
